kurento-test: Fix invalid HTML test pages & format with Prettier
HTML was invalid because '</input>' is not a valid closing tag.
SyntaxError: Void elements do not have end tags "input" (77:15)

Also, format to make humanly readable, it was a mess! Use default
Pretties.js formatting options.